### PR TITLE
Update @amsterdam/use-promise to version 3

### PR DESCRIPTION
**Pull request by jonkoops**

### CODE REVIEW

**Comment by chrisvanmook** [comment]
@jonkoops Did you got this to work in other projects that use jest?

**Comment by jonkoops** [comment]
@chrisvanmook I wanted to spend some time figuring out what is causing the issue that complains about ES modules. By all accounts this should work, bit haven't found the time to work on it.

**Comment by chrisvanmook** [comment]
Yeah I've tried to add this to the `transformIgnorePatterns` but had no effect.. Will have a better look into this later

**Comment by jonkoops** [comment]
That was my guess as well, however I think it will also have to be included in the tsconfig in order to be transformed (if the TypeScript compiler indeed does compile this). I also tried to enable ES modules in Jest but this is still too experimental.

**Pull request closed without merging**
